---
title: "Class Objectives"
format: docx
editor: source
---

## Goals of this document

We will treat this class more like a job. There will not be tests or quizzes. Rather we will have conversations where we discuss how you are doing, and what you could improve on. You will reflect on your work, I will reply and we will discuss your grade from there.

We can discuss amendment of objectives as well, especially your personal objectives.

## Basic objectives

Over the course it is expected you will:

**Technically**

1.  Understand and implement the basic R-Studio -\> GitHub workflow; be able to collaborate using GitHub.
2.  Work in Quarto files; be able to adjust format and make output look nice.
3.  Complete https://swcarpentry.github.io/r-novice-gapminder/index.html
4.  Develop slideshow and website.
5.  Use code to further your own research.

**Communications**

1.  Provide respectful feedback in class and on Slack.
2.  Assist with issues on in class and on Slack.

## Personal objectives

* Build workflowR website https://workflowr.github.io/workflowr/
* Explore using R for image analysis
* Write everything in Quarto document


## Progress tracking

* Met week of February 6, 2024 for initial conversation

## Reflection

I feel like I have put in pretty solid effort in the class, but I feel like I could put in more. I think I have let myself become a little overwhelmed with thesis work, and not taken full advantage of the opportunities to learn in this class. That being said, I have attended all class meetings, completed all homeowork and assignments, and made an effort to contribute to the class and participate. I would therefore give myself a grade of a 93%.

yay






